"""Pydantic domain and report models."""

from agnes.models.assessment import (
    ASSESSMENT_SCHEMA_VERSION,
    AssessmentContext,
    AssessmentReport,
    SubstituteAssessment,
    SubstituteAssessmentLLM,
)
from agnes.models.chat import (
    CHAT_SCHEMA_VERSION,
    ChatMessage,
    ChatRequest,
    ChatResponse,
    ChatStep,
)
from agnes.models.canonical import (
    CanonicalMaterial,
    CanonicalRegistry,
    FamilyRoleAssignment,
    FamilyRoleBatchResponse,
    RegistryCoverage,
)
from agnes.models.entities import (
    BOMComponentRow,
    BOMRow,
    CompanyRow,
    ProductRow,
    SupplierProductRow,
    SupplierRow,
)
from agnes.models.evidence import (
    EVIDENCE_SCHEMA_VERSION,
    CitationRef,
    EvidenceClaim,
    EvidenceReport,
    SubstituteEvidence,
    SubstituteEvidenceLLM,
)
from agnes.models.graph import GraphIngestReport, KGEdge, KGNode, node_id
from agnes.models.procurement import (
    PROCUREMENT_SCHEMA_VERSION,
    PriceBenchmark,
    ProcurementOrder,
    RiskTier,
    SupplierRating,
)
from agnes.models.recommendation import (
    RECOMMENDATION_SCHEMA_VERSION,
    ConsolidationOpportunity,
    RecommendationReport,
    SourcingRecommendation,
    SourcingSignals,
)
from agnes.models.reports import (
    ColumnInfo,
    EntityCounts,
    ForeignKeyInfo,
    Phase1Report,
    RepeatedMaterial,
    SchemaSummary,
    SupplierFragmentation,
    TableSummary,
)
from agnes.models.voice import (
    VOICE_SCHEMA_VERSION,
    VoiceRespondResponse,
    VoiceTimings,
    VoiceTtsRequest,
)

__all__ = [
    "ASSESSMENT_SCHEMA_VERSION",
    "CHAT_SCHEMA_VERSION",
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "ChatStep",
    "PROCUREMENT_SCHEMA_VERSION",
    "PriceBenchmark",
    "ProcurementOrder",
    "RiskTier",
    "SupplierRating",
    "RECOMMENDATION_SCHEMA_VERSION",
    "ConsolidationOpportunity",
    "RecommendationReport",
    "SourcingRecommendation",
    "SourcingSignals",
    "AssessmentContext",
    "AssessmentReport",
    "EVIDENCE_SCHEMA_VERSION",
    "BOMComponentRow",
    "BOMRow",
    "CanonicalMaterial",
    "CanonicalRegistry",
    "CitationRef",
    "ColumnInfo",
    "CompanyRow",
    "EntityCounts",
    "EvidenceClaim",
    "EvidenceReport",
    "FamilyRoleAssignment",
    "FamilyRoleBatchResponse",
    "ForeignKeyInfo",
    "GraphIngestReport",
    "KGEdge",
    "KGNode",
    "Phase1Report",
    "ProductRow",
    "RegistryCoverage",
    "RepeatedMaterial",
    "SchemaSummary",
    "SubstituteAssessment",
    "SubstituteAssessmentLLM",
    "SubstituteEvidence",
    "SubstituteEvidenceLLM",
    "SupplierFragmentation",
    "SupplierProductRow",
    "SupplierRow",
    "TableSummary",
    "VOICE_SCHEMA_VERSION",
    "VoiceRespondResponse",
    "VoiceTimings",
    "VoiceTtsRequest",
    "node_id",
]
